// Run with node tests/test_observation_client.cjs; no packages or browser required.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
    const source = fs.readFileSync(path.join(__dirname, '../static/js/eyeball-observations.js'), 'utf8');
    const { ObservationSession, repeatedInvitation } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
    let time = 0;
    const session = new ObservationSession(() => time);
    session.enter('products');
    time = 20000;
    assert.ok(!session.eligible(), 'dwell alone stays silent');
    session.selectProject('chaseingreen');
    assert.ok(!session.eligible(), 'short dwell with selection stays silent');
    time = 46000;
    session.openedDetails('chaseingreen'); session.openedDetails('chaseingreen');
    assert.ok(session.eligible(), 'combined signals eligible');
    session.markOffered();
    assert.ok(!session.eligible(), 'once per visit');
    session.enter('services'); time += 1000; session.enter('products');
    assert.ok(session.restraint().visit_offered, 'observer oscillation preserves visit');
    session.enter('services'); time += 20000; session.enter('products');
    assert.ok(!session.restraint().visit_offered, 'meaningful reentry creates new visit');
    session.selectProject('chaseingreen'); time += 200000;
    assert.ok(!session.eligible(), 'same suggestion stays suppressed across visits');
    session.selectProject('lottovate');
    assert.ok(session.eligible(), 'new product can qualify after cooldown');
    session.dismissedChat();
    assert.ok(!session.eligible(), 'dismissal suppresses page session');
    const fresh = new ObservationSession(() => time);
    assert.equal(fresh.dismissed, false, 'reload starts fresh');
    fresh.enter('products'); fresh.selectProject('chaseingreen');
    time += 90000; assert.ok(fresh.eligible(), 'explicit selection and 90s qualifies');
    fresh.clickedTestflight(); assert.ok(!fresh.eligible(), 'TestFlight suppresses offers');
    const hidden = new ObservationSession(() => time);
    time += 10000; hidden.setVisible(false); time += 100000;
    assert.equal(hidden.snapshot().time_on_section_seconds, 10, 'hidden time excluded');
    hidden.setVisible(true); time += 10000;
    assert.equal(hidden.snapshot().time_on_section_seconds, 20);
    hidden.openedChat(); hidden.sentMessage(); hidden.dismissedChat();
    assert.equal(hidden.snapshot().chat_open_count, 1);
    assert.equal(hidden.snapshot().chat_message_count, 1);
    const real = new ObservationSession(() => time);
    real.enter('products'); real.interacted('chaseingreen');
    real.interacted('chaseingreen');
    assert.equal(real.interactions,1,'focus plus click must not double count');
    time += 3000; real.interacted('chaseingreen'); time += 43000;
    assert.equal(real.snapshot().details_opened_count,0);
    assert.ok(real.eligible(),'two real interactions and dwell need no details');
    const wording='Want me to walk through ChaseInGreen with you?';
    real.markOffered(wording);
    assert.deepEqual(real.invitationTexts,[wording]);
    assert.ok(repeatedInvitation('Want me to walk through Lottovate with you?',real.invitationTexts));
    assert.deepEqual(new ObservationSession().invitationTexts,[],'wording does not survive reload');
    console.log('PASS client observation/restraint assertions');
})().catch(error => { console.error(error); process.exitCode = 1; });
