const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
const p=await b.newPage({viewport:{width:1440,height:1000}});let errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',async m=>{if(m.text().startsWith('Eyeball motion'))console.log('DEBUG',await m.args()[1]?.jsonValue());});
const state=()=>p.evaluate(async()=>(await import('/static/js/oes-core-companion.js')).getOESCoreCompanionState());
async function setup(){await p.goto(process.env.OES_TEST_URL || 'http://127.0.0.1:5055');await p.locator('[data-product="chaseingreen"] h3').scrollIntoViewIfNeeded();await p.waitForTimeout(1600);assert.equal((await state()).active,true);await p.evaluate(()=>{window.activations=0;document.addEventListener('oes:coreactivated',()=>window.activations++);});}
for(const steps of [30,2]){await setup();const core=await p.locator('[data-oes-core]').boundingBox();const before=(await state()).position;await p.mouse.move(core.x-150,core.y+core.height/2);await p.mouse.move(core.x+core.width/2,core.y+core.height/2,{steps});await p.waitForTimeout(400);assert.deepEqual((await state()).position,before);await p.mouse.click(core.x+core.width/2,core.y+core.height/2);await p.waitForTimeout(100);assert.equal(await p.locator('#eyeball-chat').evaluate(e=>e.open),true);assert.ok(await p.evaluate(()=>window.activations)>0);assert.equal((await state()).active,true);console.log('PASS approach/click + original activation + floating chat',steps);await p.keyboard.press('Escape');}
await setup();let before=(await state()).position;await p.mouse.move(800,580);await p.mouse.move(1030,600,{steps:20});await p.waitForTimeout(900);assert.deepEqual((await state()).position,before);console.log('PASS nearby text pass');
let core=await p.locator('[data-oes-core]').boundingBox();await p.mouse.move(core.x+core.width/2,core.y+core.height/2);await p.mouse.down();await p.mouse.move(core.x+core.width/2+45,core.y+core.height/2+20,{steps:10});await p.mouse.up();assert.equal(await p.locator('#eyeball-chat').evaluate(e=>e.open),false);assert.deepEqual((await state()).position,before);console.log('PASS center spin drag does not relocate or open chat');
const h=await p.locator('.oes-core-companion__movement-handle').boundingBox();await p.mouse.move(h.x+h.width/2,h.y+h.height/2);await p.mouse.down();await p.mouse.move(h.x-160,h.y-80,{steps:12});assert.equal((await state()).interaction.isDragging,true);assert.notDeepEqual((await state()).position,before);await p.mouse.up();await p.waitForTimeout(600);assert.equal((await state()).interaction.isDragging,false);assert.equal(await p.locator('#eyeball-chat').evaluate(e=>e.open),false);console.log('PASS outer handle drag and dock');
await setup();const link=p.locator('[data-product="chaseingreen"] a').filter({hasText:'Privacy Policy'});await link.scrollIntoViewIfNeeded();await p.waitForTimeout(1000);
await p.evaluate(async()=>{const a=[...document.querySelectorAll('[data-product="chaseingreen"] a')].find(e=>e.textContent.includes('Privacy Policy')).getBoundingClientRect();const c=document.querySelector('[data-oes-core]').getBoundingClientRect();const m=await import('/static/js/oes-core-companion.js');const s=m.getOESCoreCompanionState();m.moveOESCoreCompanion(a.left+a.width*.3-c.width-(c.left-s.position.x),a.top-110-(c.top-s.position.y),{manual:false,duration:0});});
await p.waitForTimeout(1100);before=(await state()).position;const r=await link.boundingBox();console.log('OBSTRUCTION SETUP',r,before);await p.mouse.move(r.x+r.width*.55,r.y-35);await p.mouse.move(r.x+r.width*.55,r.y+r.height*.35,{steps:12});await p.waitForTimeout(700);const after=(await state()).position;console.log('OBSTRUCTION RESULT',after);assert.notDeepEqual(after,before);console.log('PASS real actionable overlap relocation');
core=await p.locator('[data-oes-core]').boundingBox();await p.mouse.move(core.x+core.width/2,core.y+core.height/2,{steps:15});await p.waitForTimeout(600);assert.deepEqual((await state()).position,after);console.log('PASS following relocated Core does not cause repeated fleeing');
await link.click();await p.waitForURL('**/privacy');console.log('PASS previously obstructed privacy link activates');
await setup();before=(await state()).position;
// Exercise existing invitation visibility without spending a model request on a motion test.
await p.evaluate(()=>{document.querySelector('[data-eyeball-invitation]').hidden=false;document.dispatchEvent(new CustomEvent('oes:sectionchange',{detail:{sectionId:'client-work'}}));});
await p.waitForTimeout(700);assert.deepEqual((await state()).position,before);console.log('PASS visible invitation holds automatic section travel');
assert.deepEqual(errors,[]);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
